name: Publish Beta Package
on:
  push:
    tags:
      - "v*-beta*"

jobs:
  call-shared-pipeline:
    uses: ./.github/workflows/shared-publish.yml
    with:
      release_type: "beta"
      npm_tag: "beta"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
