name: Publish Stable Package
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch: {}

jobs:
  call-shared-pipeline:
    uses: ./.github/workflows/shared-publish.yml
    with:
      release_type: "production"
      npm_tag: "latest"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: call-shared-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      
      - name: Generate changelog
        run: |
          npm install -g auto-changelog
          auto-changelog --unreleased false --backfill-limit false --commit-limit false --starting-version v1.0.4
      
      - name: Extract release notes
        id: extract_release_notes
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          # 去掉前缀 v
          CLEAN_TAG="${RELEASE_TAG#v}"
          RELEASE_NOTES=$(awk "/## \\[?$CLEAN_TAG\\]?/{flag=1;next}/^## /{flag=0}flag" CHANGELOG.md)
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          files: |
            CHANGELOG.md
