name: Publish Stable Package
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-shared-pipeline:
    uses: ./.github/workflows/shared-publish.yml
    with:
      release_type: "production"
      npm_tag: "latest"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
